[Defaults]
# 파일명 앞에 붙일 문자열
prefix = _

# 원본 파일명과 복제 번호 사이에 넣을 문자열
suffix = .

# 기본 번호 입력 방식: count 또는 range
mode = count

# mode = count 일 때
count = 51

# mode = range 일 때
start = 101
end = 200
increment = 1
