name: Build & Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # v로 시작하는 태그를 푸시할 때 실행


permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest #ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 history와 tag를 가져오는 설정
          

      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'


      - name: uv 설치
        uses: astral-sh/setup-uv@v6
          

      - name: 의존성 동기화 (Sync)
        run: uv sync --all-extras --dev --reinstall-package file-duplicator


      - name: Get version # 실패 시 강제종료 
        shell: pwsh
        run: |
          $version = uv run python -c "from file_duplicator import __version__; print(__version__)"

          Write-Host "Git tag: $env:GITHUB_REF_NAME"
          Write-Host "Package version: $version"

          if ("v$version" -ne $env:GITHUB_REF_NAME) {
              throw "Version mismatch: Git tag is $env:GITHUB_REF_NAME but package version is $version"
          }

          "VERSION=$version" >> $env:GITHUB_ENV


      - name: Create Windows version resource
        run: uv run python scripts/create_version_info.py
          # create_version_info.py 파일을 실행해서
          # 파이썬 version_info.txt 파일 자체를 쌩으로 생성한다. (근데 이거 맞아?)


      - name: Build executable - pyinstaller 실행
        run: |
          uv run pyinstaller `
            --noconfirm `
            --noconsole `
            --onedir `
            --clean `
            --name "File-Duplicator-$env:VERSION" `
            --add-data "app_icon.ico;." `
            --icon="app_icon.ico" `
            --version-file "build/version_info.txt" `
            main.py


      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "dist/File-Duplicator-$env:VERSION" `
            -DestinationPath "dist/File-Duplicator-$env:VERSION.zip"


      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" `
            "dist/File-Duplicator-$env:VERSION.zip" `
            --title "File Duplicator $env:VERSION" `
            --generate-notes
